

location /services/inventory-service {

    proxy_pass http://172.17.0.1:5010;

}



location /services/user-service {

    proxy_pass http://172.17.0.1:5011;

}



location /services/auth-service {

    proxy_pass http://172.17.0.1:5012;

}



location /services/notification-service {

    proxy_pass http://172.17.0.1:5012;

}

