
name: CI Pipeline auth-service

on:
  push:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -R

      - name: Build Docker Image
        run: docker build -t auth-service ./services/auth-service

      - name: Verify Docker Images
        run: docker images
