global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "inventory-service"

    static_configs:
      - targets: ["172.17.0.1:5010"]

  - job_name: "auth-service"

    static_configs:
      - targets: ["172.17.0.1:5011"]

  - job_name: "notification-service"

    static_configs:
      - targets: ["172.17.0.1:5012"]

  - job_name: "user-service"

    static_configs:
      - targets: ["172.17.0.1:5013"]

  - job_name: "payment-service"

    static_configs:
      - targets: ["172.17.0.1:5014"]



  - job_name: "inventory-service"


    static_configs:

      - targets: ["172.17.0.1:5010"]

