name: Dynamic CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  detect-and-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Changed Service
        id: changed-service
        run: |

          SERVICE=$(git diff --name-only HEAD~1 HEAD | grep '^services/' | cut -d'/' -f2 | head -n 1)

          echo "SERVICE=$SERVICE" >> $GITHUB_ENV

          echo "Changed service: $SERVICE"

      - name: Build Changed Service
        run: |

          if [ -n "$SERVICE" ]; then

            docker build -t $SERVICE ./services/$SERVICE

          else

            echo "No service changes detected"

          fi

      - name: Verify Images
        run: docker images
