name: Dynamic CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build-and-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -R

      - name: Build Auth Service
        run: docker build -t auth-service ./services/auth-service || true

      - name: Build User Service
        run: docker build -t user-service ./services/user-service || true

      - name: Build Payment Service
        run: docker build -t payment-service ./services/payment-service || true

      - name: Build Inventory Service
        run: docker build -t inventory-service ./services/inventory-service || true

      - name: Build Notification Service
        run: docker build -t notification-service ./services/notification-service || true

      - name: Verify Images
        run: docker images
